title: The real new website
author: Bennington People
email: javierlopezguevara@bennington.edu
description: > # this means to ignore newlines until "baseurl:"
  1ST WEBSITE MAN!
baseurl: "/minima"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
